### ISSUE TITLE
Can't use Team Project Set

### ISSUE THREAD

**Issue by ltsolutionviet** [dandar3/android-google-firebase-messaging#1]
File > Import... > Team > Team Project Set > URL:
https://raw.githubusercontent.com/dandar3/android-google-firebase-messaging/15.0.0/.projectset

The following errors occurred while importing projects. Some projects may not be loaded.
  Projects for repository type org.eclipse.team.svn.core.svnnature could not be loaded as the type could not be found.

**Comment by dandar3** [comment]
Install the latest build of Subversive + Connectors from Polarion first.
https://polarion.plm.automation.siemens.com/products/svn/subversive/download

I would recommend SVNKit (Java based) instead of JavaHL (OS native binaries).

There used to be a video tutorial on how to install but it is not available anymore, was thinking about making one myself and make it publicly available.
https://www.eclipse.org/subversive/downloads.php

**Comment by ltsolutionviet** [comment]
I have install Subversive + Connectors in your link, but don't see option SVN .

**Comment by ltsolutionviet** [comment]
I have try to download and add many lib but not work, please help me.

**Comment by ltsolutionviet** [comment]
@dandar3 Problem when i use SVN. 
https://ibb.co/4gcLdq8

**Comment by ltsolutionviet** [comment]
This is your project, but no resource, i cant run it.
https://ibb.co/N175MBG

**Comment by ltsolutionviet** [comment]
Beside in MyProject follow your Tutorial in your Blog, i add many lib , but conflic, crash, can't run.
https://ibb.co/mF9sX21
Please have a look , help me please.

**Comment by ltsolutionviet** [comment]
Thanks for your response. I have try to Team option after setup svn.
It working.

**Comment by dandar3** [comment]
> https://ibb.co/mF9sX21

I notice you have copied JAR libraries from the Google Firebase libraris into your Demo Project libs. 

You shouldn't do that, all you need to do is download the projects through the Team Set and add `google-firebase-messaging` as a dependant library project to your app project.

As as a note, enable the `manifestmerger` into your app so that it will merge Android manifests from all dependant libraries (they are all linked together already, you don't need to do anything, only the step above for the main proiect as a dependency to your app project): https://stackoverflow.com/a/11234525
